development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_SERVER_URL") { "redis://localhost:6379/1" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_SERVER_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: demo_app_production
